### PR TITLE
Corrected Japanese translation

### PR DESCRIPTION
**Pull request by ut-64bit**
Should I change "items_displayed.credit"?

### CODE REVIEW

**Comment by FREEDINN3R** [comment]
Hey there! Thanks for the correction, I appreciate it. Yes, you should definitely add credit for yourself, so that others would know that you contributed

**Comment by ut-64bit** [comment]
I've added the credits and would like you to merge them.

**Comment by FREEDINN3R** [comment]
Thank you for your help! However, I prefer to accept merge requests only from people I personally know. Do you mind if I add your translation file myself? You'll still be credited as the author in the translation file itself.

**Comment by ut-64bit** [comment]
Yes, that's okay.

**Comment by FREEDINN3R** [comment]
Great! I will do it in the next update.

**Comment by FREEDINN3R** [comment]
Done! Thank you again for your help

**Pull request closed without merging**
